name: Push Tencent Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  test: 1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install and build
        run: |
          yarn
          yarn global add pm2
          yarn build:dev
      - name: Push
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_CLOUD_IP }} #云服务器的ip
          username: ${{ secrets.TENCENT_CLOUD_NAME }} #云服务器的用户名
          password: ${{ secrets.TENCENT_CLOUD_PASSWORD }} #云服务器的密码
          port: 22
          source: 'dist/'
          remote: 'root'
